---
# tasks file for content_check
- name: Build a list of orgs
  ansible.builtin.shell: "hammer --no-headers organization list --full-result yes --fields name"
  register: organization_dict
  changed_when: False    

- name: Show manifests on Satellite
  ansible.builtin.command: "hammer subscription list --organization {{ item }}" 
  loop: "{{ organization_dict.stdout_lines }}"
  register: result_manifests
  changed_when: False    
 
- name: Check if Simple Content Access is enabled
  ansible.builtin.command: "hammer simple-content-access status --organization {{ item }}"
  loop: "{{ organization_dict.stdout_lines }}"
  register: result_sca_enabled
  changed_when: False  

- name: Show enabled repositories
  ansible.builtin.shell: "hammer repository list --organization {{ item }} | wc -l"
  loop: "{{ organization_dict.stdout_lines }}"
  register: result_repositories
  changed_when: False    

- name: Show sync plans
  ansible.builtin.shell: "hammer --no-headers sync-plan list --organization {{ item }} | wc -l"  
  loop: "{{ organization_dict.stdout_lines }}"
  register: result_sync_plans
  changed_when: False    

- name: lifecycle environments
  ansible.builtin.shell: "hammer lifecycle-environment list --organization {{ item }}| wc -l"
  loop: "{{ organization_dict.stdout_lines }}"
  register: result_lifecycles
  changed_when: False    

- name: Show existing content views
  ansible.builtin.shell: "hammer content-view list --organization {{ item }} | wc -l "
  loop: "{{ organization_dict.stdout_lines }}"
  register: result_content_views
  changed_when: False    

- name: Show number of activation keys
  ansible.builtin.shell: "hammer --no-headers activation-key list --organization {{ item }} | wc -l"
  loop: "{{ organization_dict.stdout_lines }}"
  register: result_activation_keys
  changed_when: False    

