---
- name: Find and list the activation keys registered on the Satellite (NOTE - THIS MIGHT TAKE SOME TIME)
  ansible.builtin.shell: |
    orgs=$(hammer --csv organization list | tail -n +2)
    echo "$orgs" | while IFS=, read -r id name
    do
      echo "Activation keys for Organization: $name (ID: $id)"
      hammer activation-key list --organization-id "$id"
      echo
    done
  register: result_activation_key