- name: List all organisations associated with the Satellite Server.
  ansible.builtin.command: hammer --no-headers --output yaml organization list --full-result yes --fields id,name
  register: result_orgs

- name: Set Organisations dictionary.
  ansible.builtin.set_fact:
    shc_orgs: "{{ result_orgs.stdout | ansible.builtin.from_yaml }}"

- name: List all locations associated with the Satellite Server.
  ansible.builtin.command: hammer --no-headers --output yaml location list --per-page all --fields id,name
  register: result_locations

- name: Set Locations dictionary.
  ansible.builtin.set_fact:
    shc_locations: "{{ result_locations.stdout | ansible.builtin.from_yaml }}"

- name: List all capsule names and urls
  ansible.builtin.shell: hammer --no-headers --output yaml capsule list --per-page all --include-status true
  register: result_capsules

- name: Set Capsules dictionary.
  ansible.builtin.set_fact:
    shc_capsules: "{{ result_capsules.stdout | ansible.builtin.from_yaml }}"

