---
# tasks file for ./roles/system_reqs_check

- name: Fetch Satellite hostname
  ansible.builtin.shell: hostnamectl | grep hostname
  register: result_hostname

- name: Fetch Satellite Operating System
  ansible.builtin.shell: hostnamectl | grep System
  register: result_system

- name: Fetch Satellite IP address
  ansible.builtin.shell: ip -4 -o a | grep -v "127.0.0" | awk '{print $4}'
  register: result_ip_addr

- name: Fetch Kernel Version
  ansible.builtin.shell: uname -r
  register: result_kernel_version

- name: Determine system uptime
  ansible.builtin.shell: uptime | sed 's/.*up \([^,]*\), .*/\1/'
  register: result_uptime

- name: Find time/date of last reboot
  ansible.builtin.shell: who -b | awk '{print $3,$4}'
  register: result_reboot

- name: Find Red Hat Release version
  ansible.builtin.shell: cat /etc/redhat-release
  register: result_redhat_release

- name: Check CPU details
  ansible.builtin.shell: lscpu | grep -v Flags
  register: result_system_cpu
