---
- name: Initialise the Satellite Health Check
  hosts: #SATELLITE ADDR
  roles:
    - test-role
  tasks:
    - name: Generate the Satellite Health Check Report
      ansible.builtin.template:
        src: ./satellite_hc_report.j2
        dest: /tmp/satellite_hc_report_"{{ ansible_hostname }}"

# note to self: make sure to use -u root then --ask-pass