---
- name: Initialise the Satellite Health Check
  hosts: #satellite ip addr
  roles:
    - high_level_check
    - test-role
    - system_reqs_check
    - satellite_version_check
    - organisations_check
    - firewall_and_proxy_check
    - infrastructure_design_check
    - network_connectivity_check
    - qpidd_storage_check

  tasks:
    - name: Generate the Satellite Health Check Report
      ansible.builtin.template:
        src: ./satellite_hc_report.j2
        dest: /tmp/satellite_hc_report_"{{ ansible_hostname }}"
    
    - name: Fetch the satellite report and copy it to the local machine
      ansible.builtin.fetch:
        src: /tmp/satellite_hc_report_"{{ ansible_hostname }}"
        dest: /tmp/
        flat: yes

# note to self: make sure to use -u root then --ask-pass