---
- name: Initialise the Satellite Health Check
  hosts: localhost
  roles:
    - #TODO#
  tasks:
    - name: Generate the Satellite Health Check Report
      ansible.builtin.template:
        src: ./satellite_hc_report.j2
        dest: /tmp/satellite_hc_report_"{{ ansible_hostname }}"
