  #---
- name: Initialise the Satellite Health Check
  hosts: satellite
  roles:
    - activation_keys_check
    - auth_sources_check
    - compute_resources_check
#    - content_check --> need to fix item loops. Might be redundant
    - disk_space_check
#    - errata_check
    - firewall_and_proxy_check
    - high_level_check
    - infrastructure_design_check
#    - log_error_check --> add conditionals to stop from breaking
    - logging_check
    - network_connectivity_check
    - network_resources_check
    - organisations_check
    - qpidd_storage_check
    - registered_host_check
    - remote_execution_check
    - satellite_version_check
    - sync_plan_check
    - system_reqs_check

  tasks:
    - name: Generate the Satellite Health Check Report in .adoc format
      ansible.builtin.template:
        src: ./templates/satellite_hc_report.adoc
        dest: satellite_hc_report_{{ ansible_hostname }}.adoc

    - name: Fetch the .adoc Satellite report and copy it to the local machine
      ansible.builtin.fetch:
        src: satellite_hc_report_{{ ansible_hostname }}.adoc
        dest: ./
        flat: yes

    - name: Delete the .adoc template on the Satellite
      ansible.builtin.shell: rm -Rf satellite_hc_report_{{ ansible_hostname }}.adoc

# note to self: make sure to use -u root then --ask-pass
