---
- name: Initialise the Satellite Health Check
  hosts: # SATELLITE ADDR
  roles:
    - test-role
    - system_reqs_check
  tasks:
    - name: Generate the Satellite Health Check Report
      ansible.builtin.template:
        src: ./satellite_hc_report.j2
        dest: /tmp/satellite_hc_report_"{{ ansible_hostname }}"
    
    - name: Fetch the satellite report and copy it to the local machine
      ansible.builtin.fetch:
        src: /tmp/satellite_hc_report_"{{ ansible_hostname }}"
        dest: /tmp/
        flat: yes

# note to self: make sure to use -u root then --ask-pass