  #---
- name: Initialise the Satellite Health Check
  hosts: 10.76.23.10
  roles:
    - activation_keys_check
    - auth_sources_check
    - compute_resources_check
    - content_check
    - disk_space_check
#    - errata_check
    - firewall_and_proxy_check
    - high_level_check
    - infrastructure_design_check
    - log_error_check
    - logging_check
    - network_connectivity_check
    - network_resources_check
    - organisations_check
    - qpidd_storage_check
    - registered_host_check
    - remote_execution_check
    - satellite_version_check
    - sync_plan_check
    - system_reqs_check

  vars: 
    - satellite_server: http://10.76.23.10

# NOTE TO SELF: MAYBE DO PACKAGE CHECK?
#  - i.e. sysstat

  tasks:
#    - name: Generate the Satellite Health Check Report in .txt format
#      ansible.builtin.template:
#        src: ./templates/satellite_hc_report.j2
#        dest: satellite_hc_report_{{ ansible_hostname }}.txt

    - name: Generate the Satellite Health Check Report in .adoc format
      ansible.builtin.template:
        src: ./templates/satellite_hc_report.adoc
        dest: satellite_hc_report_{{ ansible_hostname }}.adoc

#    - name: Fetch the .txt Satellite report and copy it to the local machine
#      ansible.builtin.fetch:
#        src: satellite_hc_report_{{ ansible_hostname }}.txt
#        dest: ./
#        flat: yes

    - name: Fetch the .adoc Satellite report and copy it to the local machine
      ansible.builtin.fetch:
        src: satellite_hc_report_{{ ansible_hostname }}.adoc
        dest: ./
        flat: yes

# note to self: make sure to use -u root then --ask-pass
