  #---
- name: Initialise the Satellite Health Check
  hosts: satellite
  roles:
    - os_level_checks
    - settings_checks
    - infrastructure_checks
    - content_checks 
    # --> need to fix item loops. Might be redundant
    # errata checks also hashed out

  tasks:
    - name: Generate the Satellite Health Check Report in .adoc format
      ansible.builtin.template:
        src: ./templates/satellite_hc_report.adoc
        dest: satellite_hc_report_{{ ansible_hostname }}.adoc

    - name: Fetch the .adoc Satellite report and copy it to the local machine
      ansible.builtin.fetch:
        src: satellite_hc_report_{{ ansible_hostname }}.adoc
        dest: ./
        flat: yes

    - name: Delete the .adoc template on the Satellite
      ansible.builtin.shell: rm -Rf satellite_hc_report_{{ ansible_hostname }}.adoc

# note to self: make sure to use -u root then --ask-pass
