- name: Conduct a general status health check.
  ansible.builtin.shell:  yes no | satellite-maintain health check --plaintext
  register:               result_health_check
  changed_when:           False
  ignore_errors:          True

