- name: Conduct a general status health check.
  ansible.builtin.command: satellite-maintain health check --plaintext
  register: result_health_check

- name: Verify which services are running and enabled.
  ansible.builtin.command: satellite-maintain service list
  register: result_running_services
