- name:  Search Red Hat Satellite Services logs for error and higher precedence.
  ansible.builtin.shell:  journalctl --priority=err --unit foreman* --unit httpd --unit postgresql --unit pulp* --unit redis --unit tomcat | tail -n 100
  register:                 shc_log_sat_services
  changed_when:             False


- name:  Check Satellite Production log for errors.
  ansible.builtin.shell:  zgrep -P -e '\[[EF]\|' /var/log/foreman/production.log* | sort | head -n 100
  register:               shc_log_foreman_production
  changed_when:           False

