---
# tasks file for ./roles/firewall_and_proxy_check

- name: Report enabled firewall ports
  ansible.builtin.shell: firewall-cmd --list-ports
  register: result_firewall_ports

- name: Gather facts on TCP and UDP listening ports
  community.general.listen_ports_facts:
