:pdf-theme: ./styles/pdf/redhat-theme.yml
:pdf-fontsdir: ./fonts
:doctype: book
:subject: Automated Satellite Health Check Report
:author: JANE-DOE 
:revnumber: {gitdate}

:toc: 

= Red Hat Satellite Health Check Report 

== Introduction

This is a health check report for Satellite server {{ ansible_fqdn }} at {{ ansible_date_time.time }} on {{ ansible_date_time.date }}.

=== Disclaimer

_This health check provides a best effort evaluation of the targeted Red Hat Satellite(s). The results from the
report do not in any way provide a guarantee or warranty for the health and performance of the targeted
Satellite(s). The health check aims to provide an indication of overall health and provide consultant
recommendations on a best effort basis._

:sectnums:

== Health Check Overview:
----
{{ result_health_check.stdout }}
----

== Satellite Service Status:
----
{{ result_running_services.stdout }}
----

== Satellite Configuration

=== Base Operating System Details

*Investigation:* What version of RHEL is the Satellite server running on? What is the architecture? Is the CPU suitable to the Satellite server? is the hostname unique?

*Observation:*
----
- Hostname: {{ result_hostname.stdout | to_nice_yaml }}
- Operating System: {{ result_system.stdout | to_nice_yaml }}
- IP Address: {{ result_ip_addr.stdout | to_nice_yaml }}
- Kernel Version: {{ result_kernel_version.stdout | to_nice_yaml }}
- Uptime: {{ result_uptime.stdout | to_nice_yaml }}
- Last Reboot Time: {{ result_reboot.stdout | to_nice_yaml }}
- Red Hat Release: {{ result_redhat_release.stdout | to_nice_yaml }}
----

The CPU details are as follows:
----
{{ result_system_cpu.stdout_lines | to_nice_yaml}}
----

Is there at least 20gb of disk space available in /var?

{{ result_disk_space.stdout_lines | to_nice_yaml }}

*Guidance:* The minimum requirements for a Satellite server are as follows:

- x86_64 architecture
- The latest version of Red Hat Enterprise Linux 8 Server
- 4-core 2.0 GHz CPU at a minimum
- A minimum of 20 GB RAM is required for Satellite Server to function.

In addition, a minimum of 4GB RAM of swap space is also recommended. Satellite running with less RAM than the minimum value might not operate correctly.

For further information, please refer to the Satellite installation https://access.redhat.com/documentation/en-us/red_hat_satellite/6.13[documentation].

*Rationale:* There should be at least 20GB of space available in /var directory to perform future synchronizations. Please note that if you are to download a major release (e.g. RHEL 7 Server), you will require a minimum of 20GB per release.

It is also important to note that Red Hat Satellite's performance improves when more resources are allocated to the server. Enhanced computational power and increased memory allow for more efficient processing of tasks and data management. Higher-quality resources reduce system latency and increase throughput, making the software more responsive and capable of handling larger workloads effectively. 

{% if BASE_OS_RECOMMENDATION is defined %}
{{ BASE_OS_RECOMMENDATION }}
{% endif %}

=== Satellite and Capsule Physical Architecture
|=======
|*Investigation:*| List the names and urls of the Satellite and Capsule servers.
|*Rationale:*| Red Hat Satellite and Red Hat Satellite Capsules servers facilitate provisioning and software lifecycle management of RHEL hosts through GUI, CLI and API. 

Red Hat Satellite has fine-grained privilege separation to precisely control who can do what to which resources being managed. Red Hat Satellite Capsules mirror software content and facilitate access to Satellite services such as provisioning in segmented networks that have restricted network access.
|=======
*Observation:*

.Satellites/Capsules:
----
{{ shc_capsules | ansible.builtin.to_nice_yaml }}
----

{% if shc_PHYSICAL_ARCHITECTURE_RECOMMENDATION is defined %}
{{ shc_PHYSICAL_ARCHITECTURE_RECOMMENDATION }}
{% endif %}



=== Satellite and Capsule Logical Architecture
|=======
|*Investigation:*| List the organisations and locations associated with the Satellite server.
|*Guidance:*| Satellite should be configured with the minimum number of organisations and locations to support the required operations and configurations, without adding unhelpful and time consuming complexity.
|*Rationale:*| Red Hat Satellite uses Organizations to partition users, subscriptions and contain host provisioning and software life cycle configuration. Multiple Organizations are typically used by cloud hosting providers or teams that purchase subscriptions financially independently.

Locations divide Organizations into logical groups, not necessarialy based on geographical location. Provisioning based resources are most affected by location such as Capsules, software lifecycle environments, subnets, domains, realms and hosts. A complex capability might be thought of as a location or a small set of locations if it has its own subnets for example.  A location could also be a single rack, whatever makes sense.  However, more locations make a more complex environment.  A host that is not provisioned by Red Hat Satellite can technically register to any Capsule but the content it requires will be assigned to specific Locations.
 
|=====
*Observation:*

.Organisations:
----
{{ shc_orgs | ansible.builtin.to_nice_yaml }}
----

.Locations:
----
{{ shc_locations | ansible.builtin.to_nice_yaml }}
----

{% if shc_LOGICAL_ARCHITECTURE_RECOMMENDATION is defined %}
{{ shc_LOGICAL_ARCHITECTURE_RECOMMENDATION }}
{% endif %}



=== Satellite Version 
|======
|*Investigation:*| What is the currently installed Satellite version on the Satellite server and the capsules? What was the initial installation version?
|*Guidance:*| Red Hat provides a published product life cycle for the Red Hat Satellite server and its associated federation enablement component, the Red Hat Satellite Capsule Server, in order for customers and partners to effectively plan, deploy and support their management of Red Hat infrastructure. 

The life cycle associated with Red Hat Satellite, which encompasses stated time periods for each major version, identifies the various levels of maintenance, split into production phases, from the initial release date - or General Availability (GA) to the End of Life (EOL). It is important to ensure your Satellite is upgraded within the product life cycle to ensure that your organisation can continue to receive patching, security updates, and maintain an effective Satellite server.
|*Rationale:*| Keeping the Red Hat Satellite version up to date is crucial as it ensures that you have the latest security updates and patches released by Red Hat to keep your systems secure. Moreover, newer versions of Satellite are packaged with performance improvements and new features that can enhance the efficiency and capabilities of your Linux fleet  management.
|====== 

*Observation:* 

{{ result_satellite_version.stdout | to_nice_yaml }} is installed on the Satellite server.

{% if result_capsule_version.failed == false %}
{{ result_capsule_version.stdout | to_nice_yaml }} is installed on the Capsule server.
{% else %}
Package satellite-capsule is not installed on the Capsule Server.
{% endif %}

=== Firewalls and Proxy
|=====
|*Investigation:*| Is firewalling appropriately configured for the Satellite and Capsule servers? Is the proxy server able to access cdn.redhat.com and subscription.rhsm.redhat.com directly without SSL termination? Are the required ports open? Are any optional ports opened?
|*Guidance:*
a|
Generally, the following 12 ports should be open on the firewall:

- 80/tcp
- 443/tcp
- 5647/tcp
- 8000/tcp
- 8140/tcp 
- 8443/tcp
- 9090/tcp
- 53/tcp
- 53/udp
- 67/udp
- 69/udp
- 5000/tcp
|*Rationale:*| A Satellite system runs many services, many of which should be protected from external access. Correct configuration of firewall rules limits network traffic to only that which is necessary, improving the security of the Satellite system.
|=====
*Observation:* 
The ports that are currently open are:
---- 
{{ result_firewall_ports.stdout | to_nice_yaml }}
----

{% if FIREWALLS_RECOMMENDATION is defined %}
{{ FIREWALLS_RECOMMENDATION }}
{% endif %}

== Infrastructure

=== Network Requirements
|=====
|*Investigation:*| The network connectivity between Satellite and its capsules needs to be reliable. Can the Satellite connect to the CDN without issue? Do the FQDN, Domain, and Shortname connections resolve?
|*Guidance:*
a| 
To maintain a networked base operating system for your Satellite, the following requirements apply: 

- Full forward and reverse DNS resolution using a fully-qualified domain name
- A system umask of 0022
- Administrative user (root) access
- A current Red Hat Satellite subscription
- A unique host name, which can contain lower-case letters, numbers, dots (.) and hyphens (-)
- A minimum of 20 GB RAM is required for Satellite Server to function. In addition, a minimum of 4 GB RAM of swap space is also recommended. Satellite running with less RAM than the minimum value might not operate correctly.
- 4-core 2.0 GHz CPU at a minimum
- The latest version of Red Hat Enterprise Linux 8 or Red Hat Enterprise Linux 7 Server
|*Rationale:*| Proper DNS resolution is crucial for network stability and for services to locate and connect to the Satellite server using its domain name. A clear, unique hostname helps in easy identifcation and minimises confusion in network communication, crucial for the Satellite's interaction with its capsules and external networks. 

Using the latest RHEL version guarantees compatibility with the latest Satellite updates, security patches, and features, ensuring a stable and secure operating environment. Likewise, maintaining a curent Red Hat Satellite subscription ensures access to the latest features, features, updates, patches, and support by maintaining system reliability and performance.
|=====
*Observation:*

.Ping results:
----
{{ result_ping.stdout_lines | to_nice_yaml }}
----
.CDN Connection:
----
{{ result_cdn_conn.stdout_lines | to_nice_yaml }}
----
.Are the required ports listening?
----
{{ result_port_listen.stdout_lines | to_nice_yaml }}
----

{% if NETWORK_RECOMMENDATION is defined %}
{{ NETWORK_RECOMMENDATION }}
{% endif %}

== Storage

=== Qpidd Storage
|=====
|*Investigation:*| Is the qpidd service available? How much space is available in the qpidd partition? is the qpidd parititon too large?
|*Rationale:*| It's recommended to ensure QPIDD is properly configured with sufficient resources and tuned for the network and system environment. Regular monitoring and maintenance of the QPIDD service are essential to promptly identify and resolve any performance or connectivity issues, and to ensure it's securely configured to prevent unauthorized access.
|=====
*Observation:*

NOTE: qpidd was removed from Satellite systems with the introduction of Pulp3. No analysis will be conducted for this check if Pulp3 is present on the Satellite server.
 
Pulp3 is {% if pulp3_present == true %}installed on this Satellite Server.{% else %}absent from this Satellite Server.{% endif %}

{% if pulp3_present == false %}
{% if result_qpidd_status.failed == false %}
{{ result_qpidd_status.stdout | to_nice_yaml }}
{% else %}
{{ result_qpidd_status.stderr_lines | to_nice_yaml }}
{% endif %}

{% if result_qpidd_status.failed == false %}
{{ result_qpidd_storage.stdout | to_nice_yaml }}
{% else %}
{{ result_qpidd_storage.stderr_lines | to_nice_yaml }}
{% endif %}
{% endif %}

{% if QPIDD_RECOMMENDATION is defined %}
{{ QPIDD_RECOMMENDATION }}
{% endif %}

=== Backup/Restore Procedures
|=====
|*Investigation:*| If the client is using snapshots, what are the backups listed in foreman-maintain backups? What kinds of backup procedures are in place for the Satellite? 
|*Observation:*| The consultant will likely have to ask the client for additional information on procedures and backup philosophy.
|*Guidance:*
a| 
The frequency of backing up your Red Hat Satellite 6 instance should be determined based on a few key factors:

- *Change Frequency*: How often changes are made in your Satellite environment, such as adding new hosts, updating content, or modifying configurations. If changes are frequent, consider more frequent backups to minimize data loss.
- *Data Criticality*: The importance of the data managed by Satellite. If the data is critical for your operations, backing up regularly is essential to ensure a quick recovery in case of failure.
- *System Usage and Load*: In a highly active Satellite environment, you might need more frequent backups compared to a less active one.
- *Recovery Objectives*: Your Recovery Point Objective (RPO) and Recovery Time Objective (RTO). Determine how much data loss is acceptable and how quickly you need to be able to restore operations.
- *Resource Availability*: The resources available for backup processes, including storage space and network bandwidth. More frequent backups require more storage and can impact network performance.
|*Rationale:*| Backup and restore procedures help to ensure the continuity of your Red Hat Satellite deployment and associated data in the event of a disaster. If your deployment uses custom configurations you should take these into account when planning your backup and disaster recovery policy.
|=====

{% if BACKUP_RECOMMENDATION is defined %}
{{ BACKUP_RECOMMENDATION }}
{% endif %}

== Host Management

=== Remote Execution
|=====
|*Investigation:*| Is remote execution set up on Satellite? Is cron used to execute these remote jobs?
|*Rationale:*| Remote execution allows administrators to remotely run an arbitrary command on Satellite clients quickly and easily. This can help organisations easily standardise machine configurations, improve system-to-administrator ratios by automating patch and configuration management and provisioning, and reduce errors and inconsistencies.
|=====
*Observation:*
----
{{ result_remote_execution.stdout_lines | to_nice_yaml }}
----

{% if REMOTE_EXECUTION_RECOMMENDATION is defined %}
{{ REMOTE_EXECUTION_RECOMMENDATION }}
{% endif %}

=== Errata
|=====
|*Investigation:*| Are errata used? How is Errata managed? What errata are installable on the registered hosts?
|*Guidance:*| Administrators should regularly review and apply errata to ensure systems are protected against known vulnerabilities and are running the latest software versions. The process can be streamlined by setting up auto-apply policies for critical updates and using Satellite's filtering tools to target specific systems or environments, thereby maintaining a high standard of security and reliability across the network.
|*Rationale:*| As a part of Red Hat’s quality control and release process, we provide customers with updates for each release of official Red Hat RPMs. Red Hat compiles groups of related package into an erratum along with an advisory that provides a description of the update. Security Advisory errata describe fixed security issues found in the package. Bug Fix Advisory errata describes bug fixes, and Product Enhancement Advisory describes enhancements and new features added to the package. 
|=====
*Observation:*

NOTE: The errata variable has been omitted in the report due to size of role. Replace the variable here if you choose to include the role.

// UNCOMMENT ME AND ADD IN THE RESULT VARIABLE! 

{% if ERRATA_RECOMMENDATION is defined %}
{{ ERRATA_RECOMMENDATION }}
{% endif %}

== Satellite Management

=== Satellite Logging
|=====
|*Investigation:*| Are any errors logged in the foreman, foreman-proxy, or /var logs? Do any issues tie in with other issues identified in the report?
|*Guidance:*| Any errors that appear in the logs should be investigated to ensure that Satellite is functioning effectively and correctly to avoid bugs and security vulnerabilities. 
|*Rationale:*| Logs are essential for an effective and efficient Red Hat Satellite deployment as they provide detailed records of system operations, errors, and security events. This information is crucial for troubleshooting issues, monitoring system performance, and ensuring compliance with security and operational policies. 

By analyzing these logs, administrators can proactively address potential problems, optimize system configurations, and maintain a high level of operational efficiency and reliability in their Satellite environment.
|=====
*Observation:*

+ /var/log/foreman/production.log returns:
----
{% if result_production_log.failed == false %}
{{ result_production_log.stdout_lines | to_nice_yaml }}
{% else %}
The production.log does not contain any errors.
{% endif %}
----

+ /var/log/foreman-proxy/proxy.log returns:
----
{% if result_proxy_log.failed == false %}
{{ result_proxy_log.stdout_lines | to_nice_yaml }}
{% else %}
The proxy.log does not contain any errors.
{% endif %}
----

+ /var/log/messages returns:
----
{% if result_messages_log.failed == false %}
{{ result_messages_log.stdout_lines | to_nice_yaml }}
{% else %}
The messages log does not contain any errors.
{% endif %}
----

{% if LOGGING_RECOMMENDATION is defined %}
{{ LOGGING_RECOMMENDATION }}
{% endif %}

=== Sync Plans
|=====
|*Investigation:*| Are synchronization plans being used by the organisation? How often are these sync plans run? Which repositories are being queried at each sync run?
|*Guidance:*| A synchronization plan checks and updates the content at a scheduled date and time. In Red Hat Satellite 6, you can create a synchronization plan and assign products to the plan, which will then sync updates from the Red Hat Satellite repository and the source repositories to the Satellite Server.
|*Rationale:*| Sync plans in Red Hat Satellite are crucial for managing and automating the regular update of software repositories, ensuring that systems under management have access to the latest security patches, bug fixes, and features. 

By scheduling and controlling these updates, sync plans help maintain system stability, security, and compliance, while also allowing administrators to plan for bandwidth and system load during updates, minimizing disruption in the network. This organized approach to content management significantly enhances the efficiency and reliability of the IT infrastructure.
|=====

*Observation:*
----
{{ result_sync_plan.stdout | to_nice_yaml }}
----

{% if SYNC_PLANS_RECOMMENDATION is defined %}
{{ SYNC_PLANS_RECOMMENDATION }}
{% endif %}

=== Activation Keys
|=====
|*Investigation:*| Are activation keys used in the Satellite server? How are the activation keys used?
|*Guidance:*| For effective activation key management, ensure that the keys are organised logically and aligned with the correct lifecycle environments and content views to ensure that systems are registered correctly for streamlined updates and maintenance. It is also recommended that you use a naming convention that clearly indicates their purpose, associated lifecycle stage, or organizational unit.

Likewise, limit the number of activation keys to avoid complexity and confusion.Revoke or update keys that are no longer in use to maintain security and efficiency in your system management.
|*Rationale:*
a| Activation keys provide a method to automate system registration and subscription attachment. You can create multiple keys and associate them with different environments and Content Views. 

They can define the following properties for content hosts: 

- Associated subscriptions and subscription attachment behaviour
- Available products and repositories
- A life cycle environment and a Content View
- Host collection membership
|=====

*Observation:*

----
{{ result_activation_key.stdout | to_nice_yaml }}
----

{% if KEYS_RECOMMENDATION is defined %}
{{ KEYS_RECOMMENDATION }}
{% endif %}

=== Registered hosts

*Investigation:* How many registered hosts are connected to the Satellite? 

*Observation:*
----
{{ result_registered_hosts.stdout_lines | to_nice_yaml }}
----

{% if HOSTS_RECOMMENDATION is defined %}
{{ HOSTS_RECOMMENDATION }}
{% endif %}
