---
# tasks file for ./roles/organisations_check

- name: List all capsule names and urls
  ansible.builtin.shell: hammer capsule list
  register: result_capsule_list

- name: List organisations on master server
  ansible.builtin.command: hammer organization list
  register: result_organization_list